#!/bin/sh

case $BUTTON in
    1) pamixer --allow-boost -t   ;;
    4) pamixer --allow-boost -i 1 ;;
    5) pamixer --allow-boost -d 1 ;;
esac

vol=$(pamixer --get-volume --get-mute)

if [ -n "${vol%%false*}" ] ; then
    printf "🔇%3s%%\n" "${vol##* }"
elif [ "${vol##* }" -eq 0 ]; then
    printf "🔇%3s%%\n" "${vol##* }"
elif [ "${vol##* }" -gt 66 ]; then
    printf "🔊%3s%%\n" "${vol##* }"
elif [ "${vol##* }" -gt 33 ]; then
    printf "🔉%3s%%\n" "${vol##* }"
else
    printf "🔈%3s%%\n" "${vol##* }"
fi
